Upgrade etcd client to 3.5
IBM-Cloud/go-etcd-rules pull request #128
Opened 2022-01-24 22:28 UTC by brandondr96

This upgrades the etcd client to 3.5 and fixes the related dependencies which changed. Additionally, since `clientv3` was changed to `client/v3`, I switched the code to reference `v3` for clarity.

2022-01-25 03:52 UTC, jswarren4 requested changes
Requesting changes for now since we're not ready to switch to 3.5 yet.

2022-03-10 15:29 UTC, kramvan1 commented
Need to revert these 3.5 backports now https://github.com/IBM-Cloud/go-etcd-rules/pull/122

2022-03-10 15:30 UTC, kramvan1 requested changes
Need to revert https://github.com/IBM-Cloud/go-etcd-rules/pull/122

2022-03-10 19:54 UTC, jswarren4 submitted a review, later dismissed
Approving so my change request doesn't block merge.

2022-03-23 22:01 UTC, kramvan1 commented on Makefile
> +	docker run -d -p 2379:2379 --name etcd quay.io/coreos/etcd:v3.5.1 \
Can make this 3.5.2 now

2022-03-23 22:03 UTC, kramvan1 commented on rules/engine_test.go
> +	for i := 0; i < 60; i++ {
Might be nice to push this into a helper function.

2023-02-06 17:09 UTC, kramvan1 submitted a review, later dismissed

2023-02-06 17:39 UTC, sonaljain0 commented on go.mod
> +	go.etcd.io/etcd/client/pkg/v3 v3.5.7 // indirect
Shouldn't this be 3.5.6?

2023-02-06 17:40 UTC, sonaljain0 commented on go.sum
> +go.etcd.io/etcd/client/v3 v3.5.7/go.mod h1:sOWmj9DZUMyAngS7QQwCyAXXAL6WhgTOPLNS/NabQgw=
Lots of 3.5.7 here

2023-02-06 17:41 UTC, sonaljain0 requested changes
Added comments

2023-02-06 17:49 UTC, sonaljain0 approved these changes

2023-02-06 17:53 UTC, merged